const i18nDict = {
    // Navbar
    'nav_trust': { en: 'TRUST', id: 'KEPERCAYAAN' },
    'nav_community': { en: 'COMMUNITY', id: 'KOMUNITAS' },
    'nav_economy': { en: 'ECONOMY', id: 'EKONOMI' },
    'nav_utility': { en: 'UTILITY', id: 'UTILITAS' },
    'nav_transparency': { en: 'TRANSPARENCY', id: 'TRANSPARANSI' },
    'nav_enter': { en: 'ENTER FORTRESS', id: 'MASUK PORTAL' },
    
    // Hero
    'hero_subtitle': { en: 'Sovereign Economic Infrastructure', id: 'Infrastruktur Ekonomi Berdaulat' },
    'hero_desc': { en: 'A community-centered digital economic infrastructure connecting people, commerce, distribution, assets, and transparent technology.', id: 'Infrastruktur ekonomi digital berpusat pada komunitas yang menghubungkan manusia, perdagangan, distribusi, aset, dan teknologi transparan.' },
    'hero_btn': { en: 'EXPLORE ARCHITECTURE', id: 'JELAJAHI ARSITEKTUR' },

    // Sections
    'sec_trust_title': { en: 'Building Digital Economic Trust Through Transparency and Responsible Technology.', id: 'Membangun Kepercayaan Ekonomi Digital Melalui Transparansi dan Teknologi Bertanggung Jawab.' },
    'sec_comm_title': { en: 'People Before Technology.', id: 'Manusia Sebelum Teknologi.' },
    'sec_comm_desc': { en: 'Technology is only a tool. People and their productive activities are the true foundation of this ecosystem. We build infrastructure to empower human coordination, not replace it.', id: 'Teknologi hanyalah alat. Manusia dan aktivitas produktif mereka adalah pondasi sejati ekosistem ini. Kami membangun infrastruktur untuk memberdayakan koordinasi manusia, bukan menggantikannya.' },
    'sec_econ_title': { en: 'Value Originates From Economic Activity.', id: 'Nilai Berasal Dari Aktivitas Ekonomi.' },
    'sec_econ_desc': { en: 'Economic value is generated by productive activity, coordination, and commerce. Our infrastructure serves to support this flow.', id: 'Nilai ekonomi dihasilkan oleh aktivitas produktif, koordinasi, dan perdagangan. Infrastruktur kami hadir untuk mendukung aliran ini.' },
    'sec_util_title': { en: 'Technology Supporting Everyday Economic Activity.', id: 'Teknologi Pendukung Aktivitas Ekonomi Sehari-hari.' },
    'sec_block_title': { en: 'Transparent Infrastructure Layer.', id: 'Lapisan Infrastruktur Transparan.' },
    'sec_portal_title': { en: 'PORTAL ACCESS', id: 'AKSES PORTAL' },
    'sec_portal_desc': { en: 'Access ecosystem tools and community infrastructure. Requires active Web3 identification.', id: 'Akses alat ekosistem dan infrastruktur komunitas. Membutuhkan identifikasi Web3 aktif.' },
    
    // Dapp
    'dapp_back': { en: 'BACK TO MAIN', id: 'KEMBALI KE UTAMA' },
    'dapp_connect': { en: 'CONNECT WALLET', id: 'KONEK WALLET' },
    'dapp_bal_title': { en: 'Total Balance (Wallet)', id: 'Total Saldo (Wallet)' },
    'dapp_status_title': { en: 'Sovereign Status', id: 'Status Kedaulatan' },
    'dapp_status_val': { en: 'ACTIVE', id: 'AKTIF' },
    'dapp_wd_title': { en: 'Ready to Withdraw', id: 'Siap Ditarik' },
    'dapp_btn_harvest': { en: 'Harvest', id: 'Panen' },
    'dapp_btn_wd': { en: 'Withdraw', id: 'Tarik' },
    'dapp_tab_staking': { en: 'Join Protocol', id: 'Gabung Protokol' },
    'dapp_tab_network': { en: 'Network & Rank', id: 'Jaringan & Pangkat' },
    'dapp_tab_assets': { en: 'Request Asset', id: 'Minta Aset' },
    'dapp_tab_p2p': { en: 'P2P Portal', id: 'Portal P2P' }
};

let currentLang = localStorage.getItem('snr_lang') || 'en';

function switchLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('snr_lang', lang);
    
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (i18nDict[key] && i18nDict[key][lang]) {
            el.innerText = i18nDict[key][lang];
        }
    });
    
    document.querySelectorAll('.lang-btn').forEach(btn => {
        if(btn.dataset.lang === lang) {
            btn.classList.add('bg-primary', 'text-black', 'font-bold');
            btn.classList.remove('text-secondary', 'hover:text-white');
        } else {
            btn.classList.remove('bg-primary', 'text-black', 'font-bold');
            btn.classList.add('text-secondary', 'hover:text-white');
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    switchLanguage(currentLang);
});
