import re

with open('index.html', 'r', encoding='utf-8') as f:
    html = f.read()

replacements = {
    # Navbar
    '<a href="#trust" class="nav-link">TRUST</a>': '<a href="#trust" class="nav-link" data-i18n="nav_trust">TRUST</a>',
    '<a href="#community" class="nav-link">COMMUNITY</a>': '<a href="#community" class="nav-link" data-i18n="nav_community">COMMUNITY</a>',
    '<a href="#economy" class="nav-link">ECONOMY</a>': '<a href="#economy" class="nav-link" data-i18n="nav_economy">ECONOMY</a>',
    '<a href="#utility" class="nav-link">UTILITY</a>': '<a href="#utility" class="nav-link" data-i18n="nav_utility">UTILITY</a>',
    '<a href="#transparency" class="nav-link">TRANSPARENCY</a>': '<a href="#transparency" class="nav-link" data-i18n="nav_transparency">TRANSPARENCY</a>',
    
    # Hero
    '<span>Sovereign Economic Infrastructure</span>': '<span data-i18n="hero_subtitle">Sovereign Economic Infrastructure</span>',
    'A community-centered digital economic infrastructure connecting people, commerce, distribution, assets, and transparent technology.': '<span data-i18n="hero_desc">A community-centered digital economic infrastructure connecting people, commerce, distribution, assets, and transparent technology.</span>',
    'EXPLORE ARCHITECTURE': '<span data-i18n="hero_btn">EXPLORE ARCHITECTURE</span>',
    
    # Trust
    'Building Digital Economic Trust Through Transparency and Responsible Technology.': '<span data-i18n="sec_trust_title">Building Digital Economic Trust Through Transparency and Responsible Technology.</span>',
    
    # Community
    'People Before Technology.': '<span data-i18n="sec_comm_title">People Before Technology.</span>',
    'Technology is only a tool. People and their productive activities are the true foundation of this ecosystem. We build infrastructure to empower human coordination, not replace it.': '<span data-i18n="sec_comm_desc">Technology is only a tool. People and their productive activities are the true foundation of this ecosystem. We build infrastructure to empower human coordination, not replace it.</span>',
    
    # Economy
    'Value Originates From Economic Activity.': '<span data-i18n="sec_econ_title">Value Originates From Economic Activity.</span>',
    'Economic value is generated by productive activity, coordination, and commerce. Our infrastructure serves to support this flow.': '<span data-i18n="sec_econ_desc">Economic value is generated by productive activity, coordination, and commerce. Our infrastructure serves to support this flow.</span>',
    
    # Utility
    'Technology Supporting Everyday Economic Activity.': '<span data-i18n="sec_util_title">Technology Supporting Everyday Economic Activity.</span>',
    
    # Blockchain
    'Transparent Infrastructure Layer.': '<span data-i18n="sec_block_title">Transparent Infrastructure Layer.</span>',
    
    # Portal Access
    'PORTAL ACCESS</h3>': 'PORTAL ACCESS</h3>', # Need to inject data-i18n inside h3, I'll do this below with regex
    'Access ecosystem tools and community infrastructure. Requires active Web3 identification.': '<span data-i18n="sec_portal_desc">Access ecosystem tools and community infrastructure. Requires active Web3 identification.</span>',
    
    # Dapp
    'BACK TO MAIN': '<span data-i18n="dapp_back">BACK TO MAIN</span>',
    'CONNECT WALLET': '<span data-i18n="dapp_connect">CONNECT WALLET</span>',
    'Total Saldo (Wallet)': '<span data-i18n="dapp_bal_title">Total Saldo (Wallet)</span>',
    'Status Kedaulatan': '<span data-i18n="dapp_status_title">Status Kedaulatan</span>',
    'AKTIF</h3>': 'AKTIF</h3>',
    'Ready to Withdraw</p>': 'Ready to Withdraw</p>',
    'Harvest\n': 'Harvest\n',
    'Withdraw\n': 'Withdraw\n',
    'Join Protocol\n': 'Join Protocol\n',
    'Jaringan & Rank\n': 'Jaringan & Rank\n',
    'Request Asset\n': 'Request Asset\n',
    'P2P Portal\n': 'P2P Portal\n',
}

for k, v in replacements.items():
    html = html.replace(k, v)

# Special cases
html = html.replace('<h3 class="text-3xl font-display font-bold mb-4">PORTAL ACCESS</h3>', '<h3 class="text-3xl font-display font-bold mb-4" data-i18n="sec_portal_title">PORTAL ACCESS</h3>')
html = html.replace('<h3 class="text-2xl font-bold text-accent">AKTIF</h3>', '<h3 class="text-2xl font-bold text-accent" data-i18n="dapp_status_val">AKTIF</h3>')
html = html.replace('<p class="text-secondary text-sm mb-1">Ready to Withdraw</p>', '<p class="text-secondary text-sm mb-1" data-i18n="dapp_wd_title">Ready to Withdraw</p>')
html = html.replace('Harvest\n                            </button>', 'Harvest</span>\n                            </button>').replace('Harvest\n', '<span data-i18n="dapp_btn_harvest">Harvest\n')
html = html.replace('Withdraw\n                            </button>', 'Withdraw</span>\n                            </button>').replace('Withdraw\n', '<span data-i18n="dapp_btn_wd">Withdraw\n')
html = html.replace('Join Protocol\n                    </button>', 'Join Protocol</span>\n                    </button>').replace('Join Protocol\n', '<span data-i18n="dapp_tab_staking">Join Protocol\n')
html = html.replace('Jaringan & Rank\n                    </button>', 'Jaringan & Rank</span>\n                    </button>').replace('Jaringan & Rank\n', '<span data-i18n="dapp_tab_network">Jaringan & Rank\n')
html = html.replace('Request Asset\n                    </button>', 'Request Asset</span>\n                    </button>').replace('Request Asset\n', '<span data-i18n="dapp_tab_assets">Request Asset\n')
html = html.replace('P2P Portal\n                    </button>', 'P2P Portal</span>\n                    </button>').replace('P2P Portal\n', '<span data-i18n="dapp_tab_p2p">P2P Portal\n')

# Toggle Button injection
navbar_original = '''<div class="flex items-center">
                    <a href="#" onclick="toggleDapp(true); return false;" class="px-5 py-2.5 rounded border border-primary text-primary font-display font-bold text-sm hover:bg-primary hover:text-[#050816] transition-all duration-300 shadow-[0_0_15px_rgba(255,204,0,0.2)] hover:shadow-[0_0_25px_rgba(255,204,0,0.5)] flex items-center gap-2">
                        ENTER FORTRESS
                    </a>
                </div>'''
navbar_new = '''<div class="flex items-center gap-4">
                    <div class="flex items-center bg-[#050816] border border-cardBorder rounded overflow-hidden">
                        <button onclick="switchLanguage('en')" data-lang="en" class="lang-btn px-3 py-1 text-xs font-display transition-colors">EN</button>
                        <button onclick="switchLanguage('id')" data-lang="id" class="lang-btn px-3 py-1 text-xs font-display transition-colors">ID</button>
                    </div>
                    <a href="#" onclick="toggleDapp(true); return false;" class="px-5 py-2.5 rounded border border-primary text-primary font-display font-bold text-sm hover:bg-primary hover:text-[#050816] transition-all duration-300 shadow-[0_0_15px_rgba(255,204,0,0.2)] hover:shadow-[0_0_25px_rgba(255,204,0,0.5)] flex items-center gap-2">
                        <span data-i18n="nav_enter">ENTER FORTRESS</span>
                    </a>
                </div>'''

html = html.replace(navbar_original, navbar_new)

# Inject i18n script
script_tag = '<script src="i18n.js"></script>\n</body>'
html = html.replace('</body>', script_tag)

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(html)
print("SUCCESS")
